### PR TITLE
SDK updated version submodule

### PR DESCRIPTION
**Pull request by joseic**

### CODE REVIEW

**Comment by Mekki78** [comment]
Hi Joseic,

Could you please update the module version.

Thank you,
Regards,

**Comment by joseic** [comment]
Hi,

I've just pushed the new version number (1.0.8)

**Comment by Quetzacoalt91** [comment]
Hi,

Because of the week end, your PR won't be accepted today
We will do our best to make the changes available on Monday.

**Comment by Quetzacoalt91** [comment]
Hi @joseic,

As planned, your PR has just been merged and the changes should be available for tomorrow.

Best regards

**Comment by odelvalle** [comment]
Hi @Quetzacoalt91. @joseic  

The latest update (1.0.8) , again , does not include the latest version of the SDK

**Comment by joseic** [comment]
Yes, I'm afraid so...

I've checked the repository and it looks right, the library/sdk submodule
is pointing to the proper SDK tree:

https://github.com/nimblepayments/sdk-php/tree/80b7a6116aad39c40b11fd2f2338e3f02fd97855

[image: Imágenes integradas 1]

Please, let us know if we have to proceed with something else


2015-10-05 10:07 GMT+02:00 Omar del Valle <notifications@github.com>:

**Comment by Quetzacoalt91** [comment]
Hi,

Indeed, the update process seems to be incomplete. We are investigating on our side.

Best regards

**Pull request merged**
